# Exercise on Functions:

# Task-1

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_units(conversion_type, value, conversion_option):

    if conversion_type == 'length':
        if conversion_option == 'm to ft':
            return value * 3.28084  # 1 meter = 3.28084 feet
        elif conversion_option == 'ft to m':
            return value * 0.3048   # 1 foot = 0.3048 meters
        else:
            raise ValueError("Unsupported conversion option for length.")
    elif conversion_type == 'weight':
        if conversion_option == 'kg to lbs':
            return value * 2.20462  # 1 kilogram = 2.20462 pounds
        elif conversion_option == 'lbs to kg':
            return value * 0.453592  # 1 pound = 0.453592 kilograms
        else:
            raise ValueError("Unsupported conversion option for weight.")
    elif conversion_type == 'volume':
        if conversion_option == 'L to gal':
            return value * 0.264172  # 1 liter = 0.264172 gallons
        elif conversion_option == 'gal to L':
            return value * 3.78541  # 1 gallon = 3.78541 liters
        else:
            raise ValueError("Unsupported conversion option for volume.")
    else:
        raise ValueError("Unsupported conversion type.")

def main():
    print("Welcome to the Unit Conversion Program!")
    print("Conversion Types: length, weight, volume")

    conversion_type = input("Please enter the conversion type: ").strip().lower()

    if conversion_type == "length":
        print("\nConversion options for length:")
        print("  m to ft: Convert meters to feet")
        print("  ft to m: Convert feet to meters")
        conversion_option = input("Enter your conversion option (m to ft/ft to m): ").strip()
    elif conversion_type == "weight":
        print("\nConversion options for weight:")
        print("  kg to lbs: Convert kilograms to pounds")
        print("  lbs to kg: Convert pounds to kilograms")
        conversion_option = input("Enter your conversion option (kg to lbs/lbs to kg): ").strip()
    elif conversion_type == "volume":
        print("\nConversion options for volume:")
        print("  L to gal: Convert liters to gallons")
        print("  gal to L: Convert gallons to liters")
        conversion_option = input("Enter your conversion option (L to gal/gal to L): ").strip()
    else:
        print("Unsupported conversion type.")
        return  # Exit the program if conversion type is invalid

    try:
        value = float(input("\nEnter the value to be converted: "))
    except ValueError:
        print("Invalid input. Please enter a numeric value.")
        return

    try:
        result = convert_units(conversion_type, value, conversion_option)
        print(f"\nConverted value: {result}")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


Welcome to the Unit Conversion Program!
Conversion Types: length, weight, volume
Please enter the conversion type: volume

Conversion options for volume:
  L_to_gal: Convert liters to gallons
  gal_to_L: Convert gallons to liters
Enter your conversion option (L_to_gal/gal_to_L):  gal_to_L

Enter the value to be converted: 20

Converted value: 75.7082


# Task-2

Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
def sum_of_numbers(numbers):

    return sum(numbers)

def average_of_numbers(numbers):

    if len(numbers) == 0:
        raise ValueError("Cannot compute average of an empty list.")
    return sum(numbers) / len(numbers)

def max_of_numbers(numbers):

    if len(numbers) == 0:
        raise ValueError("Cannot determine maximum of an empty list.")
    return max(numbers)

def min_of_numbers(numbers):

    if len(numbers) == 0:
        raise ValueError("Cannot determine minimum of an empty list.")
    return min(numbers)

def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    operation = input("Enter the operation number (1-4): ").strip()

    # Prompt the user to input a list of numbers separated by spaces.
    num_str = input("Enter a list of numbers (separated by spaces): ")

    try:
        numbers = [float(num) for num in num_str.split()]
    except ValueError:
        print("Invalid input. Please ensure you enter numbers separated by spaces.")
        return

    if not numbers:
        print("No numbers entered. Please provide at least one number.")
        return

    try:
        if operation == "1":
            result = sum_of_numbers(numbers)
            print("Sum of numbers:", result)
        elif operation == "2":
            result = average_of_numbers(numbers)
            print("Average of numbers:", result)
        elif operation == "3":
            result = max_of_numbers(numbers)
            print("Maximum of numbers:", result)
        elif operation == "4":
            result = min_of_numbers(numbers)
            print("Minimum of numbers:", result)
        else:
            print("Invalid operation selection.")
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the operation number (1-4): 4
Enter a list of numbers (separated by spaces): 2 5 8 0 1
Minimum of numbers: 0.0


# Exercise on List Manipulation:

Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):

    return lst[::2]

def get_sublist(lst, start, end):

    return lst[start:end+1]

def reverse_list(lst):

    return lst[::-1]

def remove_first_last(lst):

    return lst[1:-1]

def get_first_n(lst, n):

    return lst[:n]

def get_last_n(lst, n):

    return lst[-n:]

def reverse_skip(lst):

    return lst[-2::-2]

# Testing the functions with sample input
if __name__ == "__main__":
    sample_list = [1, 2, 3, 4, 5, 6]

    print("Original List:", sample_list)
    print("1. Every other element:", extract_every_other(sample_list))
    print("2. Sublist from index 2 to 4:", get_sublist(sample_list, 2, 4))
    print("3. Reversed list:", reverse_list(sample_list))
    print("4. Remove first and last:", remove_first_last(sample_list))
    print("5. First 3 elements:", get_first_n(sample_list, 3))
    print("6. Last 2 elements:", get_last_n(sample_list, 2))
    print("7. Reverse skip (every second element from the end):", reverse_skip(sample_list))


Original List: [1, 2, 3, 4, 5, 6]
1. Every other element: [1, 3, 5]
2. Sublist from index 2 to 4: [3, 4, 5]
3. Reversed list: [6, 5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4, 5]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [5, 6]
7. Reverse skip (every second element from the end): [5, 3, 1]


# Exercise on Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
# 1. Flatten a Nested List (one level deep)
def flatten(lst):
    # Assumes lst is a list of lists.
    return [item for sub in lst for item in sub]

# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    for i in indices:
        lst = lst[i]
    return lst

# 3. Sum of All Elements in a Nested List (regardless of depth)
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    new_lst = []
    for item in lst:
        if isinstance(item, list):
            new_lst.append(remove_element(item, elem))
        else:
            if item != elem:
                new_lst.append(item)
    return new_lst

# 5. Find the Maximum Element in a Nested List (regardless of depth)
def find_max(lst):
    m = float('-inf')
    for item in lst:
        if isinstance(item, list):
            m = max(m, find_max(item))
        else:
            m = max(m, item)
    return m

# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# 7. Deep Flatten a List (arbitrary depth)
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# 8. Nested List Average
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat) if flat else 0


# Example usage:
if __name__ == "__main__":
    # 1. Flatten a Nested List
    print("Flatten:", flatten([[1, 2], [3, 4], [5]]))

    # 2. Access Nested List Element
    print("Access Nested Element:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))

    # 3. Sum of All Elements in a Nested List
    print("Sum Nested:", sum_nested([[1, 2], [3, [4, 5]], 6]))

    # 4. Remove Specific Element from a Nested List
    print("Remove Element (2):", remove_element([[1, 2], [3, 2], [4, 5]], 2))

    # 5. Find the Maximum Element in a Nested List
    print("Find Max:", find_max([[1, 2], [3, [4, 5]], 6]))

    # 6. Count Occurrences of an Element in a Nested List
    print("Count Occurrences (2):", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

    # 7. Deep Flatten a List of Lists of Lists
    print("Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

    # 8. Nested List Average
    print("Average Nested:", average_nested([[1, 2], [3, 4], [5, 6]]))


Flatten: [1, 2, 3, 4, 5]
Access Nested Element: 6
Sum Nested: 21
Remove Element (2): [[1], [3], [4, 5]]
Find Max: 6
Count Occurrences (2): 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average Nested: 3.5


# NumPy

# Problem-1:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

ones_array = np.ones((4, 2))
print("\nAll one array (4x2):")
print(ones_array)

full_array = np.full((3, 3), 7)
print("\nArray of shape (3x3) filled with 7:")
print(full_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros like the given array:")
print(zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes like the given array:")
print(ones_like_array)

new_list = [1, 2, 3, 4]
np_array_from_list = np.array(new_list)
print("\nNumPy array converted from list [1,2,3,4]:")
print(np_array_from_list)


Empty array (2x2):
[[1.81755847e-316 0.00000000e+000]
 [6.92587939e-310 6.92587938e-310]]

All one array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array of shape (3x3) filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like the given array:
[[0 0]
 [0 0]]

Ones like the given array:
[[1 1]
 [1 1]]

NumPy array converted from list [1,2,3,4]:
[1 2 3 4]


# Problem-2:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

```
# This is formatted as code
```



In [ ]:
import numpy as np

# 1. Array with values from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)

# 2. 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(arr2)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:")
print(identity_matrix)

# 4. Random array of size 30 and its mean
random_array = np.random.random(30)
mean_val = random_array.mean()
print("\nRandom array of size 30:")
print(random_array)
print("Mean of random array:", mean_val)

# 5. 10x10 random array with minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n10x10 random array:")
print(random_10x10)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

# 6. Zero array of size 10 with the 5th element replaced by 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with the 5th element replaced by 1:")
print(zero_array)

# 7. Reverse array [1, 2, 0, 0, 4, 0]
arr3 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr3[::-1]
print("\nOriginal array:", arr3)
print("Reversed array:", reversed_arr)

# 8. 2D array with 1 on the border and 0 inside (5x5)
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside (5x5):")
print(arr8)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, 0::2] = 1
checkerboard[0::2, 1::2] = 1
print("\n8x8 checkerboard pattern:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.06654532 0.68368044 0.5766792  0.28631124 0.32866654 0.10806898
 0.47528569 0.16654663 0.22391461 0.57679452 0.23160298 0.47623929
 0.09569614 0.38835377 0.51915468 0.00926346 0.83169464 0.09919826
 0.9090068  0.58723775 0.24515266 0.9722535  0.98380971 0.23264735
 0.57452098 0.57261133 0.1731478  0.9828103  0.92978409 0.6252014 ]
Mean of random array: 0.46439600195199426

10x10 random array:
[[0.6729719  0.45547771 0.77159901 0.51498222 0.11018489 0.45222383
  0.75266818 0.76261712 0.58257237 0.64906726]
 [0.77116172 0.95755919 0.01994922 0.67263916 0.36090162 0.37888695
  0.75918757 0.73184504 0.55809345 0.25107568]
 [0.06640767 0.21480279 0.9569203  0.2946116  0.4884767  0.70355082
  0.80323

# Problem-3:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x + y:")
print(x + y)

print("\nx - y:")
print(x - y)

print("\n3 * x:")
print(3 * x)

print("\nSquare of each element in x:")
print(np.square(x))

print("\nDot product of v and w:")
print(np.dot(v, w))

print("\nDot product of x and v:")
print(np.dot(x, v))

print("\nDot product of x and y:")
print(np.dot(x, y))

print("\nConcatenation of x and y along rows:")
print(np.concatenate((x, y), axis=0))

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
print("\nConcatenation of v and w along columns:")
print(np.concatenate((v_col, w_col), axis=1))

print("\nAttempting to concatenate x and v:")
try:
    print(np.concatenate((x, v), axis=0))
except Exception as e:
    print("Error:", e)
    print("Explanation: x is a 2D array with shape", x.shape, "and v is a 1D array with shape", v.shape,
          "so they cannot be concatenated without reshaping.")


x + y:
[[ 6  8]
 [10 13]]

x - y:
[[-4 -4]
 [-4 -3]]

3 * x:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]

Attempting to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array with shape (2, 2) and v is a 1D array with shape (2,) so they cannot be concatenated without reshaping.


# Problem-4:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
print("A * A_inv:")
print(A @ A_inv)

AB = A @ B
BA = B @ A
print("\nAB:")
print(AB)
print("BA:")
print(BA)

print("\n(AB).T:")
print((A @ B).T)
print("B.T @ A.T:")
print(B.T @ A.T)

M = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
b = np.array([-1, -3, 9])

x_via_inv = np.linalg.inv(M) @ b
print("\nSolution using inverse:")
print(x_via_inv)

x_via_solve = np.linalg.solve(M, b)
print("\nSolution using np.linalg.solve:")
print(x_via_solve)

A * A_inv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]

(AB).T:
[[23 51]
 [13 29]]
B.T @ A.T:
[[23 51]
 [13 29]]

Solution using inverse:
[ 2.  1. -2.]

Solution using np.linalg.solve:
[ 2.  1. -2.]
